#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (c) 2026 vivo Mobile Communication Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Generate the Rust catalog describing the boot system image.

Each `--file <VFS path>,<artifact>` pair and each entry from an optional
`--layout <json>` describes one file the kernel installs into the root tmpfs at
boot. The catalog records only *where the file lives in the VFS* and *which host
file to read it from*; the bytes are streamed in at boot over semihosting and
are never embedded in the kernel image.

`inputs` on the calling GN action keep the artifact targets built, but the
generated catalog depends on their paths alone, not their contents.

Usage: gen_boot_seed_files.py --catalog-out <file.rs> \
          --file /apps/hello/app.elf,/abs/path/bin/hello \
          --file /system/lib/libc.so.1,/abs/path/lib/liblibrs.so \
          [--layout /abs/path/app_layout.json]
"""

import argparse
import json
import os


def parse_file(spec):
    vfs_path, separator, artifact = spec.partition(",")
    if not separator or not vfs_path.startswith("/") or not artifact:
        raise SystemExit(f"invalid VFS path,artifact pair: {spec!r}")
    # Bundle layouts record their artifacts relative to the build directory,
    # which is also this action's working directory. The kernel opens the path
    # at run time from QEMU, so it has to be absolute by then.
    artifact = os.path.abspath(artifact)
    if not os.path.isfile(artifact):
        raise SystemExit(f"boot seed artifact missing: {artifact}")
    return {"vfs_path": vfs_path, "artifact": artifact}


def collect_entries(files, layouts):
    entries = [parse_file(spec) for spec in files]

    for layout_path in layouts:
        with open(layout_path, encoding="utf-8") as handle:
            layout = json.load(handle)
        for item in layout:
            entries.append(
                parse_file(f'{item["vfs_path"]},{item["artifact"]}'))

    paths = [entry["vfs_path"] for entry in entries]
    if len(paths) != len(set(paths)):
        raise SystemExit("duplicate boot seed VFS path")
    return entries


def c_literal(path):
    """Render `path` as a Rust `c"..."` literal.

    Semihosting opens the artifact by host path, so the path has to survive
    verbatim into the kernel. Reject anything that is not representable instead
    of silently mangling it.
    """
    if '"' in path or "\\" in path or "\n" in path or "\0" in path:
        raise SystemExit(
            f"boot seed artifact path is not a plain C string: {path!r}")
    return f'c"{path}"'


def write_catalog(entries, output):
    with open(output, "w", encoding="utf-8") as handle:
        handle.write("// Generated by gen_boot_seed_files.py — do not edit.\n")
        handle.write("#![no_std]\n\n")
        handle.write("/// One file of the boot system image.\n")
        handle.write("///\n")
        handle.write(
            "/// `path` is where it lands in the root tmpfs; `host_path`\n")
        handle.write(
            "/// is the host file the kernel streams in over semihosting.\n")
        handle.write("pub struct BootSeedFile {\n")
        handle.write("    pub path: &'static str,\n")
        handle.write("    pub host_path: &'static core::ffi::CStr,\n")
        handle.write("}\n\n")
        handle.write("pub static FILES: &[BootSeedFile] = &[\n")
        for entry in entries:
            path = json.dumps(entry["vfs_path"])
            handle.write(
                f"    BootSeedFile {{ path: {path}, host_path: {c_literal(entry['artifact'])} }},\n"
            )
        handle.write("];\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--catalog-out", required=True)
    parser.add_argument("--file",
                        action="append",
                        default=[],
                        help="VFS path,artifact pair to install")
    parser.add_argument("--layout",
                        action="append",
                        default=[],
                        help="app layout JSON (vfs_path/artifact, repeatable)")
    args = parser.parse_args()

    entries = collect_entries(args.file, args.layout)
    write_catalog(entries, args.catalog_out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
